name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb07b1933cea95c77192503f0d16b5299f03aface21926556ae0bcb00bc48a56"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
