name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d292f3e7572879e5894a625b4b26503f1b943e348273ee6addf6c35dc4b955b7"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
