name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3394f5bab0945b1fb5af1615642d80d1f4682fd2ba8ecd07dad01cf3342dd395"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
