#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 12 13:13:03 UTC 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=5
shaderPack=Epoch_Shader_v1.3.3.zip
enableShaders=true
