name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4883ae71c41a9746751beb568e2545211e8236f180b6f10ef2941c5bbc0107b"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
