name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f58ef5c43335de526919c51810cbf89264848c2d2285d41bd44a20ba17a7290"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
