name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "942f40ea7967a2a20d60b68fa98b5f3188513d7e8fd70ed3823ba011b2d065e5"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
